import { useEffect, useMemo } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { jsPDF } from 'jspdf';

import { useWifiSession } from '@/hooks/useWifiSession';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import {
  Check,
  Loader2,
  Circle,
  User,
  Calendar,
  Activity,
  Download,
} from 'lucide-react';

const MONITORING_STEPS = [
  'System Initialised',
  'Measuring Skin Temperature',
  'Auscultation Started',
  'Measuring HR & SpO₂',
  'Final Analysis',
];

function getConnectionBadge(state: string | null) {
  if (!state || state === 'CREATED')
    return { label: 'Waiting for Device', className: 'bg-muted text-muted-foreground' };

  if (state === 'ERROR')
    return { label: 'Error', className: 'bg-destructive text-destructive-foreground' };

  if (state === 'COMPLETED')
    return {
      label: 'Completed',
      className:
        'bg-[hsl(var(--success))] text-[hsl(var(--success-foreground))]',
    };

  return { label: 'Monitoring Live', className: 'bg-primary text-primary-foreground' };
}

const Monitor = () => {
  const { sessionId } = useParams<{ sessionId: string }>();
  const navigate = useNavigate();

  const {
    session,
    sessionState,
    statusHistory,
    vitalData,
    error,
    loadSessionById,
    loading, // 🔥 from hook
  } = useWifiSession();

  /* 🔥 LOAD SESSION ONLY ONCE */
  useEffect(() => {
    if (sessionId) {
      loadSessionById(sessionId);
    }
  }, [sessionId]);

  /* 🔥 AUTO NAVIGATE WHEN COMPLETED */
  useEffect(() => {
    if (sessionState === 'COMPLETED' && vitalData) {
      navigate(`/report/${sessionId}`, {
        state: { vital: vitalData, session },
      });
    }
  }, [sessionState, vitalData]);

  /* 🔥 STEP TRACKING */
  const currentStepIndex = useMemo(() => {
    if (!statusHistory.length) return -1;

    const latest = statusHistory[statusHistory.length - 1].message;

    return MONITORING_STEPS.findIndex(step =>
      latest.toLowerCase().includes(step.toLowerCase())
    );
  }, [statusHistory]);

  const badge = getConnectionBadge(sessionState);

  /* 🔥 LOADING SKELETON (Mobile Fix) */
  if (loading || !sessionState) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <Loader2 className="h-10 w-10 animate-spin text-primary" />
      </div>
    );
  }

  /* 📄 PDF GENERATION */
  const downloadPdf = () => {
    if (!session || !vitalData) return;

    const doc = new jsPDF();

    doc.setFontSize(16);
    doc.text('AURA-STETH AI – Clinical Report', 20, 20);

    doc.setFontSize(11);
    doc.text(`Patient Name: ${session.user_name}`, 20, 40);
    doc.text(`Age: ${session.age}`, 20, 48);
    doc.text(`Gender: ${session.gender}`, 20, 56);
    doc.text(`Mode: ${session.mode}`, 20, 64);

    doc.text('Vitals Summary', 20, 80);
    doc.text(`Skin Temperature: ${vitalData.temp ?? '--'} °C`, 20, 90);
    doc.text(`Heart Rate: ${vitalData.hr ?? '--'} bpm`, 20, 98);
    doc.text(`SpO₂: ${vitalData.spo2 ?? '--'} %`, 20, 106);
    doc.text(`Audio Peak: ${vitalData.audio ?? '--'}`, 20, 114);
    doc.text(`Overall Status: ${vitalData.status}`, 20, 122);

    doc.text('Generated by AURA-STETH AI', 20, 150);

    doc.save(`AURA_STETH_Report_${session.id}.pdf`);
  };

  return (
    <div className="min-h-screen bg-background px-4 py-6">
      <div className="mx-auto max-w-md space-y-6">

        {/* HEADER */}
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-3">
          <div className="flex items-center justify-between">
            <h1 className="text-lg font-bold">Monitoring</h1>
            <Badge className={badge.className}>{badge.label}</Badge>
          </div>

          {session && (
            <Card>
              <CardContent className="flex gap-4 p-4 text-sm">
                <div className="flex items-center gap-1.5">
                  <User className="h-3.5 w-3.5" />
                  {session.user_name}
                </div>
                <div className="flex items-center gap-1.5">
                  <Calendar className="h-3.5 w-3.5" />
                  Age {session.age}
                </div>
                <div className="flex items-center gap-1.5">
                  <Activity className="h-3.5 w-3.5" />
                  {session.mode}
                </div>
              </CardContent>
            </Card>
          )}
        </motion.div>

        {/* MONITORING STEPS */}
        {sessionState !== 'CREATED' && sessionState !== 'COMPLETED' && (
          <div className="space-y-3">
            {MONITORING_STEPS.map((step, i) => {
              const isCompleted = i < currentStepIndex;
              const isActive = i === currentStepIndex;

              return (
                <Card
                  key={step}
                  className={
                    isActive
                      ? 'border-primary bg-primary/10'
                      : isCompleted
                      ? 'border-green-500/30 bg-green-500/5'
                      : 'opacity-40'
                  }
                >
                  <CardContent className="flex gap-3 p-4">
                    {isCompleted ? (
                      <Check />
                    ) : isActive ? (
                      <Loader2 className="animate-spin" />
                    ) : (
                      <Circle />
                    )}
                    <p>{step}</p>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        )}

        {/* PDF DOWNLOAD */}
        {sessionState === 'COMPLETED' && vitalData && (
          <Button onClick={downloadPdf} className="w-full gap-2">
            <Download className="h-4 w-4" />
            Download Clinical PDF Report
          </Button>
        )}

        {/* ERROR */}
        {error && (
          <Card className="border-destructive bg-destructive/10">
            <CardContent className="p-4 text-sm text-destructive">
              {error}
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
};

export default Monitor;