import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { useEffect, useState, useMemo } from 'react';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { supabase } from '@/integrations/supabase/client';
import type { Vital, Session } from '@/types/database';
import {
  Thermometer,
  HeartPulse,
  Droplets,
  Volume2,
  RefreshCw,
  Download,
} from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

import { analyzeVitals } from '@/lib/clinicalEngine';

const Report = () => {
  const { sessionId } = useParams<{ sessionId: string }>();
  const location = useLocation();
  const navigate = useNavigate();

  const [vital, setVital] = useState<Vital | null>(
    (location.state as any)?.vital ?? null
  );
  const [session, setSession] = useState<Session | null>(
    (location.state as any)?.session ?? null
  );

  /* ================= FETCH ON REFRESH ================= */
  useEffect(() => {
    if (!vital && sessionId) {
      supabase
        .from('vitals')
        .select('*')
        .eq('session_id', sessionId)
        .order('created_at', { ascending: false })
        .limit(1)
        .maybeSingle()
        .then(({ data }) => {
          if (data) setVital(data as Vital);
        });
    }

    if (!session && sessionId) {
      supabase
        .from('sessions')
        .select('*')
        .eq('id', sessionId)
        .maybeSingle()
        .then(({ data }) => {
          if (data) setSession(data as Session);
        });
    }
  }, [sessionId, vital, session]);

  /* ================= CLINICAL ANALYSIS ================= */
  const clinical = useMemo(() => {
    if (!vital) return null;
    return analyzeVitals(vital);
  }, [vital]);

  const riskColor =
    clinical?.riskLevel === 'HIGH'
      ? 'text-red-500'
      : clinical?.riskLevel === 'MODERATE'
      ? 'text-yellow-500'
      : 'text-green-500';

  const qualityColor =
    clinical?.dataQuality === 'POOR'
      ? 'text-red-500'
      : clinical?.dataQuality === 'PARTIAL'
      ? 'text-yellow-500'
      : 'text-green-500';

  /* ================= PDF GENERATION ================= */
  const generatePDF = () => {
    if (!vital || !session || !clinical) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, pageWidth, 30, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text('AURA-STETH AI – Clinical Report', 14, 18);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);

    let y = 45;

    doc.text(`Patient: ${session.user_name}`, 14, y); y += 6;
    doc.text(`Age: ${session.age} | Gender: ${session.gender}`, 14, y); y += 6;
    doc.text(`Mode: ${session.mode}`, 14, y); y += 6;
    doc.text(`Session ID: ${session.id}`, 14, y); y += 6;
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, y);

    y += 10;

    autoTable(doc, {
      startY: y,
      head: [['Parameter', 'Measured', 'Flag']],
      body: [
        ['Temperature', vital.temp ?? '—', clinical.abnormalFields.some(f => f.includes('Temperature')) ? 'Abnormal' : 'Normal'],
        ['Heart Rate', vital.hr ?? '—', clinical.abnormalFields.some(f => f.includes('Heart Rate')) ? 'Abnormal' : 'Normal'],
        ['SpO₂', vital.spo2 ?? '—', clinical.abnormalFields.some(f => f.includes('SpO₂')) ? 'Abnormal' : 'Normal'],
        ['Audio Peak', vital.audio ?? '—', 'Info'],
      ],
      headStyles: { fillColor: [37, 99, 235] },
      styles: { fontSize: 10 },
    });

    const finalY = (doc as any).lastAutoTable.finalY + 15;

    doc.setFontSize(12);
    doc.text('Clinical Risk Assessment', 14, finalY);

    doc.setFontSize(10);
    doc.text(`Risk Level: ${clinical.riskLevel}`, 14, finalY + 8);
    doc.text(`Risk Score: ${clinical.riskScore}/100`, 14, finalY + 15);
    doc.text(`Data Quality: ${clinical.dataQuality}`, 14, finalY + 22);

    doc.text(
      doc.splitTextToSize(clinical.summary, pageWidth - 28),
      14,
      finalY + 32
    );

    doc.setFontSize(8);
    doc.text(
      'Confidential Medical Document • Generated by AURA-STETH AI',
      pageWidth / 2,
      285,
      { align: 'center' }
    );

    doc.save(`AURA_Clinical_Report_${session.id}.pdf`);
  };

  if (!vital || !session || !clinical) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        Loading Report...
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background px-4 py-6">
      <div className="mx-auto max-w-md space-y-6">

        {/* HEADER */}
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
          <h1 className="text-xl font-bold">Clinical Report</h1>
          <p className="text-sm text-muted-foreground">
            {session.user_name} • Age {session.age}
          </p>
        </motion.div>

        {/* RISK CARD */}
        <Card>
          <CardContent className="p-6 text-center space-y-2">
            <p className="text-xs uppercase tracking-wider text-muted-foreground">
              Risk Assessment
            </p>
            <p className={`text-3xl font-bold ${riskColor}`}>
              {clinical.riskLevel}
            </p>
            <p className="text-sm text-muted-foreground">
              Score: {clinical.riskScore}/100
            </p>
            <p className={`text-xs font-medium ${qualityColor}`}>
              Data Quality: {clinical.dataQuality}
            </p>
          </CardContent>
        </Card>

        {/* VITAL CARDS */}
        <div className="grid grid-cols-2 gap-3">
          {[
            { icon: Thermometer, label: 'Temperature', value: vital.temp ?? '—', abnormal: clinical.abnormalFields.some(f => f.includes('Temperature')) },
            { icon: HeartPulse, label: 'Heart Rate', value: vital.hr ?? '—', abnormal: clinical.abnormalFields.some(f => f.includes('Heart Rate')) },
            { icon: Droplets, label: 'SpO₂', value: vital.spo2 ?? '—', abnormal: clinical.abnormalFields.some(f => f.includes('SpO₂')) },
            { icon: Volume2, label: 'Audio', value: vital.audio ?? '—', abnormal: false },
          ].map((v) => (
            <Card key={v.label} className={v.abnormal ? 'border-red-500 border-2' : ''}>
              <CardContent className="flex flex-col items-center p-4">
                <v.icon className="h-6 w-6 mb-2" />
                <p className="text-xs text-muted-foreground">{v.label}</p>
                <p className={`text-xl font-bold ${v.abnormal ? 'text-red-500' : ''}`}>
                  {v.value}
                </p>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* SUMMARY */}
        <Card>
          <CardContent className="p-4 text-sm space-y-2">
            <p className="font-semibold">Clinical Summary</p>
            <p>{clinical.summary}</p>
            {clinical.recommendations.length > 0 && (
              <ul className="list-disc list-inside text-muted-foreground">
                {clinical.recommendations.map((r, i) => (
                  <li key={i}>{r}</li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>

        <Button onClick={generatePDF} className="w-full gap-2">
          <Download className="h-4 w-4" />
          Download Advanced Clinical PDF
        </Button>

        <Button onClick={() => navigate('/new-session')} className="w-full gap-2">
          <RefreshCw className="h-4 w-4" />
          Start New Session
        </Button>

      </div>
    </div>
  );
};

export default Report;